"""
Config file for the Wurf-Coach-Projekt.
"""

CAMERA_INDEX: int = 0
FRAME_WIDTH: int = 320
FRAME_HEIGHT: int = 240
MIN_MOTION_AREA: int = 500
THRESHOLD_VALUE: int = 25
DILATE_ITERATIONS: int = 2
THROW_HISTORY_LENGTH: int = 8
THROW_MIN_UPWARD_DELTA: int = 20
THROW_COOLDOWN_FRAMES: int = 30
THROW_ZONE_START_RATIO: float = 0.65
THROW_ZONE_END_RATIO: float = 0.35
EVALUATION_HISTORY_LENGTH: int = 8
EVALUATION_GOOD_DELTA: int = 35
SHOW_GRAY_WINDOW: bool = True
SHOW_MASK_WINDOW: bool = True
DRAW_THROW_ZONE: bool = True
THROW_ZONE_RATIO: float = 0.4
